version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: task_1_root_password
      MYSQL_DATABASE: task_1_database
      MYSQL_USER: task_1_user
      MYSQL_PASSWORD: task_1_password
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
